### ISSUE TITLE
ws.on is not a function

### ISSUE THREAD

**Issue by mbrevoort** [BeepBoopHQ/beepboop-js#2]
```
/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/lib/resourcer.js:20
      .on('open', handledOpen)
       ^

TypeError: ws.on is not a function
    at Resourcer.resourcer.connect (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/lib/resourcer.js:20:8)
    at new reconnect (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/node_modules/back/reconnect.js:19:12)
    at Back.backoff (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/node_modules/back/index.js:20:20)
    at retry (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/lib/retry.js:18:10)
    at WebSocket.handledError (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/lib/resourcer.js:93:5)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at ClientRequest.response (/usr/src/app/node_modules/beepboop-botkit/node_modules/beepboop/node_modules/ws/lib/WebSocket.js:696:12)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)

npm info khaledbot@1.1.0 Failed to exec start script
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
```

**Comment by mbrevoort** [comment]
@selfcontained
